// <auto-generated />
using CafeShop.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeShop.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251031161600_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Cafe"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Tea"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Cookie"
                        });
                });

            modelBuilder.Entity("CafeShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cà phê pha phin truyền thống với sữa đặc, vị đậm đà và béo ngậy.",
                            ListPrice = 45000.0,
                            Name = "Cà phê sữa đá",
                            Price = 42000.0,
                            Price100 = 38000.0,
                            Price50 = 40000.0,
                            ProductCode = "CF001",
                            Size = "M"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Trà đào tươi kết hợp cam vàng và sả, vị ngọt thanh mát.",
                            ListPrice = 55000.0,
                            Name = "Trà đào cam sả",
                            Price = 52000.0,
                            Price100 = 47000.0,
                            Price50 = 50000.0,
                            ProductCode = "TD001",
                            Size = "L"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bánh ngọt kiểu Ý với lớp kem mascarpone mềm mịn và cacao thơm lừng.",
                            ListPrice = 65000.0,
                            Name = "Bánh tiramisu",
                            Price = 62000.0,
                            Price100 = 57000.0,
                            Price50 = 60000.0,
                            ProductCode = "BK001",
                            Size = "M"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sự kết hợp tinh tế giữa vị ngọt của vải tươi và hương thơm quyến rũ của hoa hồng.",
                            ListPrice = 59000.0,
                            Name = "Trà vải hoa hồng",
                            Price = 56000.0,
                            Price100 = 51000.0,
                            Price50 = 54000.0,
                            ProductCode = "TC001",
                            Size = "L"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Trà trái cây tươi mát với ổi hồng chín mọng, mang đến hương vị ngọt dịu tự nhiên.",
                            ListPrice = 57000.0,
                            Name = "Trà ổi hồng",
                            Price = 54000.0,
                            Price100 = 49000.0,
                            Price50 = 52000.0,
                            ProductCode = "TC002",
                            Size = "L"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Trà nhài kết hợp vị ngọt thanh của đào và ổi, mang hương thơm dịu nhẹ và sảng khoái.",
                            ListPrice = 60000.0,
                            Name = "Trà nhài đào ổi",
                            Price = 57000.0,
                            Price100 = 52000.0,
                            Price50 = 55000.0,
                            ProductCode = "TC003",
                            Size = "L"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
